const types = {
    REQUEST_GET_CONTRIBUTIONS: 'REQUEST_GET_CONTRIBUTION',
    SUCCESS_GET_CONTRIBUTIONS: 'SUCCESS_GET_CONTRIBUTION',
    FAILED_GET_CONTRIBUTIONS: 'FAILED_GET_CONTRIBUTION',
}

export default types