const types = {
    SET_INITIAL: 'SET_INITIAL',
    
    REQUEST_ADD_AGENDA: 'REQUEST_ADD_AGENDA',
    SUCCESS_ADD_AGENDA: 'SUCCESS_ADD_AGENDA',
    FAILED_ADD_AGENDA: 'FAILED_ADD_AGENDA',

    REQUEST_COMPLETED_TASK: 'REQUEST_COMPLETED_TASK',
    SUCCESS_COMPLETED_TASK: 'SUCCESS_COMPLETED_TASK',
    FAILED_COMPLETED_TASK: 'FAILED_COMPLETED_TASK',
}

export default types